name: 'build-qt-on-debian8-pipeline-action'
description: 'Creates a Qt build container on Debian 8 and builds the application.'
branding:
  icon: 'command'
  color: 'red'
inputs:
  recipe:
    description: 'file with build parameters'
    default: '.build_pipe_vars.sh'
  os_name:
    description: ''
    default: 'debian'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    os_name: OSI
  args:
    - recipe=${{ inputs.recipe }}
    - build-arg os_name=${{ inputs.os_name }}
