name: 'build-qt-on-debian8-pipeline-action'
description: 'Creates a Qt build container on Debian 8 and builds the application.'
branding:
  icon: 'command'
  color: 'red'
inputs:
  recipe:
    description: 'file with build parameters'
    default: '.build_pipe_vars.sh'
  os_name:
    description: ''
    default: 'fedora'
  os_release:
    description: ''
    default: '30'
runs:
  using: 'composite'
  steps:
    - run: echo test ${{ inputs.os_name }} lalalala
      shell: bash
    - run: echo PLATT=${{ inputs.os_name }} >/tmp/ENV_OS_NAME
      shell: bash
    - run: pwd; ls -la; cat /etc/os-release
      shell: bash
    - run: echo ${{ github.action_path }}; ls -la ${{ github.action_path }}
      shell: bash
    - run: docker --version
      shell: bash
    - run: cd ${{ github.action_path }} && docker build -t build-container --build-arg os_name=${{ inputs.os_name }} --build-arg os_release=${{ inputs.os_release }} .
      shell: bash
    #- uses: ./.github/actions/multibuild
