name: 'qt-build-image-test-action'
description: 'Runs Qt build container test'
branding:
  icon: 'command'
  color: 'red'
inputs:
  command:
    description: 'command to run'
    required: false
  recipe:
    description: 'file with build parameters'
    default: '.build_pipe_vars.sh'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - recipe=${{ inputs.recipe }}
