name: 'build-qt-on-debian8-pipeline-action'
description: 'Creates a Qt build container on Debian 8 and builds the application.'
branding:
  icon: 'command'
  color: 'red'
inputs:
  recipe:
    description: 'file with build parameters'
    default: '.build_pipe_vars.sh'
  os_name:
    description: ''
    default: 'debian'
runs:
  using: 'composite'
  steps:
    - run: echo test ${{ inputs.os_name }} lalalala
      shell: bash
    - run: echo PLATT=${{ inputs.os_name }} >/ENV_OS_NAME
      shell: bash
    - using: 'docker'
      image: 'Dockerfile'
      args:
        - recipe=${{ inputs.recipe }}
        - build-arg os_name=${{ inputs.os_name }}
