name: 'build-qt-on-debian8-pipeline-action'
description: 'Creates a Qt build container on Debian 8 and builds the application.'
branding:
  icon: 'command'
  color: 'red'
inputs:
  recipe:
    description: 'file with build parameters'
    default: '.build_pipe_vars.sh'
  os_name:
    description: ''
    default: 'debian'
runs:
  using: 'composite'
  steps:
    - run: echo test ${{ inputs.os_name }} lalalala
      shell: bash
    - run: echo PLATT=${{ inputs.os_name }} >/tmp/ENV_OS_NAME
      shell: bash
    - run: pwd; ls -la; cat /etc/os-release
      shell: bash
    - run: docker --version
      shell: bash
    - uses: ./.github/actions/multibuild
