FROM fedora:30

# Build essentials
RUN \
    dnf install -y \
    perl-version git gcc-c++ compat-openssl10-devel harfbuzz-devel double-conversion-devel libzstd-devel at-spi2-atk-devel dbus-devel mesa-libGL-devel \
    libxcb libxcb-devel xcb-util xcb-util-devel xcb-util-*-devel libX11-devel libXrender-devel libxkbcommon-devel libxkbcommon-x11-devel libXi-devel libdrm-devel libXcursor-devel libXcomposite-devel 

# WebKit
RUN \
    dnf install -y \
    flex bison gperf libicu-devel libxslt-devel ruby

# WebEngine
RUN \
    dnf install -y \
    freetype-devel fontconfig-devel pciutils-devel nss-devel nspr-devel ninja-build gperf cups-devel pulseaudio-libs-devel libcap-devel alsa-lib-devel bison libXrandr-devel libXcomposite-devel libXcursor-devel libXtst-devel dbus-devel fontconfig-devel alsa-lib-devel rh-nodejs12-nodejs rh-nodejs12-nodejs-devel

# Multimedia
RUN \
    dnf install -y \
    pulseaudio-libs-devel alsa-lib-devel gstreamer1-devel gstreamer1-plugins-base-devel wayland-devel



# Run build scripts
COPY build*.sh *.tar.* *.AppImage /var/tmp/
ENTRYPOINT ["/var/tmp/build_src.sh"]
