name: 'build-qt-on-ubuntu'
description: 'Creates a Qt build container on Ubuntu 18.04 and builds the application.'
branding:
  icon: 'command'
  color: 'red'
inputs:
  recipe:
    description: 'file with build parameters'
    default: '.build_pipe_vars.sh'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - recipe=${{ inputs.recipe }}
